name: 每分钟更新个性化主题

on:
  schedule:
    - cron: "* * * * *"

jobs:
  update-theme:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v2
      
    - name: 提交并推送
      run: |
        git config user.name "Plasma4004"
        git config user.email "Plasma_mc@outlook.com"
        git push Plasma4004 main  # 替换成你的主分支名称
